Tahoe\Bundle\MultiTenancyBundle\Entity\Tenant:
    type: mappedSuperclass
    table: th_mt_tenant
    indexes:
        subdomain_idx:
            columns: [subdomain]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
        subdomain:
            type: string
