Tahoe\Bundle\MultiTenancyBundle\Entity\TenantUser:
    type: entity
    table: th_mt_tenant_user
    repositoryClass: Tahoe\Bundle\MultiTenancyBundle\Repository\TenantUserRepository
    id:
        tenant:
            associationKey: true
        user:
            associationKey: true
    fields:
        roles:
            type: array
    manyToOne:
        tenant:
            targetEntity: Tahoe\Bundle\MultiTenancyBundle\Model\MultiTenantTenantInterface
            inversedBy: tenantUsers
            joinColumn:
                name: tenant
                referencedColumnName: id
        user:
            targetEntity: Tahoe\Bundle\MultiTenancyBundle\Model\MultiTenantUserInterface
            inversedBy: tenantUsers
            joinColumn:
                name: user
                referencedColumnName: id
            cascade: ["persist", "merge"]
    lifecycleCallbacks: {  }
