services:
    invitation_crud_controller:
        class: Tahoe\Bundle\CrudBundle\Controller\CrudController
        calls:
            - [ setContainer, [@service_container] ]
            - [ setRepository, [@invitation_repository]]
            - [ setFactory, [@invitation_factory]]
            -
              - setParameters
              -
                -
                  entityName: Invitation
                  bundleName: TahoeMultiTenancyBundle
                  formType:   invitation_form

    tenantuser_crud_controller:
        class: Tahoe\Bundle\MultiTenancyBundle\Controller\TenantUserController
        calls:
            - [ setContainer, [@service_container] ]
            - [ setRepository, [@tenant_user_repository]]
            - [ setFactory, [@tenant_user_factory]]
            -
              - setParameters
              -
                -
                  entityName: TenantUser
                  bundleName: TahoeMultiTenancyBundle
                  formType:   tenantuser_form
