parameters:
#    tahoe_multi_tenancy.example.class: Tahoe\Bundle\MultiTenancyBundle\Example
services:
    tahoe.multi_tenancy.tenant_resolver:
        class: Tahoe\Bundle\MultiTenancyBundle\Service\TenantResolver
        arguments:
            - @request_stack
            - %domain%
            - @tenant_repository
    tahoe.multi_tenancy.tenant_aware_router:
        class: Tahoe\Bundle\MultiTenancyBundle\Service\TenantAwareRouter
        arguments:
            - @request_stack
            - %domain%
            - @router
    kernel.listener.tenant_aware_listener:
        class: Tahoe\Bundle\MultiTenancyBundle\EventListener\TenantAwareListener
        arguments:
            - @doctrine.orm.entity_manager
            - @tahoe.multi_tenancy.tenant_resolver
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
